spring:
  mvc:
    log-request-details: true
  output:
    ansi:
      enabled: always





name: '天下无双'

person:
  name: "素还真"
  age: 1000

logging:
  level:
    web: debug
    cn.mapper: debug
mybatis:
  mapper-locations: classpath:sqlMap/*.xml
  type-aliases-package: cn.entity
  configuration:
      map-underscore-to-camel-case: true
server:
  port: 8087




